#
#Fri Jun 12 13:14:47 IST 2026
acceptInsecureCerts=true
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, test-type, no-sandbox, ignore-certificate-errors, --window-size\=1920,1080, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, disable-dev-shm-usage, disable-extensions, disable-web-security, disable-translate, disable-logging, --headless\=new, --crash-dumps-dir\=/tmp, --disable-background-networking, --disable-client-side-phishing-detection, --disable-component-update, remote-allow-origins\=*, --headless\=chrome, --headless], extensions\=[]}
